datenight/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'date_posts#index'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :date_posts

end

datenight/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
        can :read, Post

        can [:create, :update, :destroy], Post do |post|
          post.user == user

       end




    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

datenight/app/models/activity.rb
class Activity < ApplicationRecord
  has_many :date_posts
end

datenight/app/models/activity_two.rb
class ActivityTwo < ApplicationRecord
  has_many :date_posts
end

datenight/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

datenight/app/models/date_post.rb
class DatePost < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  belongs_to :food
  belongs_to :activity_two
end

datenight/app/models/food.rb
class Food < ApplicationRecord
  has_many :date_posts
end

datenight/app/models/user.rb
class User < ApplicationRecord
  has_many :date_posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

datenight/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
   include CanCan::ControllerAdditions
end

datenight/app/controllers/date_posts_controller.rb
class DatePostsController < ApplicationController

before_filter :authenticate_user!

  def last
    @date = @user.date_posts.last
  end

  # index
  def index
    @user = current_user
    @dates = @user.date_posts.all
    @dates = DatePost.all.limit(4).order("created_at desc")
	end

  # show
  def show
   @user = current_user
   @date = DatePost.find(params[:id])

	end

  # new
  def new
    @user = current_user
		@date = DatePost.new
	end

  # create
  def create
    @user = current_user
    @date = @user.date_posts.build(date_params)
    # @date = DatePost.new(date_params)

    if @date.save
      redirect_to @date
    else
      render 'new'
    end
  end

  # edit
  def edit
    @user = current_user
    @date = DatePost.find(params[:id])
  end

  # update
  def update
    @user = current_user
    @date = DatePost.find(params[:id])

    if @date.update(date_params)
      redirect_to @date
    else
      render 'edit'
    end
  end
  # destroy
  def destroy
    @user = current_user
    @date = DatePost.find(params[:id])

    @date.destroy
    redirect_to date_posts_path
  end

  private
  def date_params
    params.require(:date_post).permit(:title, :act1, :act2, :food, :location, :user_id, :food_id, :activity_id, :activity_two_id)
  end
end

datenight/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

datenight/app/helpers/application_helper.rb
module ApplicationHelper
end

datenight/app/helpers/dates_helper.rb
module DatesHelper
end

datenight/app/helpers/welcome_helper.rb
module WelcomeHelper
end

datenight/app/views/date_posts/_form.html.erb
<div class="formContainer">
	<div class="back-fill">
		<%= form_for @date do |f| %>

			<div class="heading">
				<%= f.label :"Title:" %><br>
				<%= f.text_field :title %><br>
			</div>
			<div class="heading">
				<%= f.label :"Activity 1:" %><br>
				<!-- <%= f.text_field :act1 %><br> -->
				<%= f.collection_select :activity_id, Activity.all, :id, :name %><br>
			</div>

		  <div class="heading">
		    <%= f.label :"Food:" %><br>
		    <!-- <%= f.text_field :food %><br> -->
				<%= f.collection_select :food_id, Food.all, :id, :name %>
		  </div>

			<div class="heading">
				<%= f.label :"Activity 2:" %><br>
				<!-- <%= f.text_field :act1 %><br> -->
				<%= f.collection_select :activity_two_id, Activity.all, :id, :name %><br>
			</div>

		  <div class="heading">
		    <%= f.label :"Location:" %><br>
		    <%= f.text_field :location %><br>
		  </div>

		  <div class="heading">
		    <%=f.submit %>
		  </div>
		<% end %>
	</div>
</div>

datenight/app/views/date_posts/edit.html.erb
<h1>Edit Date</h1>

<%= render 'form' %>

datenight/app/views/date_posts/index.html.erb
<h1>Your Dates</h1>

<div class="container">
  <div>
    <ul>
      <li><%= link_to 'Create', new_date_post_path(@date), :class => "btn btn-default btn-lg" %></li>
    </ul>
  </div>
</div>

<!-- Most recent date div -->

<div class="back-fill">
<!-- From here down is lower div -->
    <div class="container">
      <!-- <div class="row"> -->
      <% if @dates.length > 0 %>
          <% @dates.each do |date| %>
                 <div class="custom_card">
                   <div class="card blue-grey darken-1">
                     <div class="card-content white-text">
                       <span class="card-title">
                         <h4>
                           <%= date.title %>
                         </h4>
                       </span>
                       <p>
                         <h6>Activity 1:</h6>
                           <%= date.activity.name %>
                         <h6>Food:</h6>
                           <%= date.food.name %>
                         <h6>Activity 2 </h6>
                           <%= date.activity_two.name %>
                         <h6>Location: </h6>
                           <%= date.location %>
                       </p>
                       </div>
                         <div class="card-action">
                              <%= link_to 'Show', date_post_path(date) %>
                              <%= link_to 'Edit', edit_date_post_path(date) %>
                              <%= link_to 'Destroy', date_post_path(date),
                                              method: :delete,
                                              data: { confirm: 'Are you sure?'} %>
                        </div>
                      </div>
                    </div>
        <% end %>
      <% else %>
        <h1>Create a New Date!</h1>
      <% end %>
</div>
</div>

datenight/app/views/date_posts/new.html.erb
<%= render 'form' %>

datenight/app/views/date_posts/show.html.erb
<div class="container">
<div class="card-panel">
<h1>THE DATE</h1>
</div>
</div>

<div class="formContainer">
	<div class="back-fill">
	<%= form_for @date do |f| %>

		<div class="heading">
			<%= f.label :Title %><br>
			<%= @date.title %><br>
		</div>
		<div class="heading">
			<%= f.label :activity %><br>
			<%= @date.activity.name %><br>
		</div>
	  <div class="heading">
	    <%= f.label :Food %><br>
	    <%= @date.food.name %><br>
	  </div>
	  <div class="heading">
	    <%= f.label :Activity2 %><br>
	    <%= @date.activity_two.name %><br>

	  </div>
	  <div class="heading">
	    <%= f.label :Location %><br>
	    <%= @date.location %><br>
	  </div>


	<% end %>
	</div>

  <%= link_to 'Edit', edit_date_post_path(@date) %>
	<br>
  <%= link_to 'Go to Dates', date_posts_path(@date) %>

datenight/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datenight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
  </head>



  <body>
    <nav>
     <% if user_signed_in? %>
      <ul>
        <li> Current User: <strong><%= current_user.email %></strong> </li>
     		<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
  	 <% else %>
     		<%= link_to "Sign up", new_user_registration_path %> |
     		<%= link_to "Login", new_user_session_path  %>
   	<% end %>
  </nav>

    <%= yield %>



   </body>
</html>

datenight/app/views/welcome/index.html.erb
<h1>It's Date Night</h1>